#!/usr/bin/Rscript

## First step, generate random bipartite graphs with different structural properties.
#source('graphs.rewiring.r')  

## Second step, simulate the stochastic LV model
source('slv1.r')

#graphs  # a set of graphs with different nestedness generated by <graph.rewiring.r> should have been designated
if (!exists('graphs.20')) stop('The graphs does not exist, please generate and assign the graphs!')

beta0 = 1
## get the perfect nested graph, i.e., the last graph
graph = graphs.20[[length(graphs)]]$B
## get the lagest [gamma0] that allow the positive definition for all the graphs
gamma0 = get.gamma0.max(graph, beta0 = beta0)

sigma0 = 0.1
h = 0

sub.graphs.num = 18  # samping uniformly from the set of graphs
graphs.index = floor(seq(from = 1, to = length(graphs.20), length.out = sub.graphs.num))
A = laply(graphs.index, function(index) {
  sim.slv1.graph(graphs.20[[index]]$B, beta0 = beta0, gamma0 = gamma0, sigma0 = sigma0)
})


## Input: A four dimensional array, which is the output of simulation of Stochastic LV model
## First dimension: the index of graphs with increasing nestedness
## Second dimension: the number of simulation of Stochastic LV2 model
## Third dimension: the time steps of simulation
## Fourth dimension: the number of species
## Output: the mean vector and variance-covariance matrix, and the parameters like gamma0, sigma0, h

slv1.means.and.vars = alply(A,.parallel = TRUE, .margins = c(1), function(one) {
  print(1)
  one.means = aaply(one, .margins = c(2, 3), mean)
  one.means = one.means[5002:10001, ]
  one.means.mean = aaply(one.means, .margins = c(2), mean)
  
  one.vars = aaply(one, .margins = c(2), var)
  one.vars = one.vars[5002:10001, , ]
  one.vars.mean = aaply(one.vars, .margins = c(2, 3), mean)
  
  list(means = one.means.mean, vars = one.vars.mean)
})

slv1.means.and.vars[[length(slv1.means.and.vars) + 1]] = list(gamma0 = gamma0, sigma0 = sigama0, h = h)

filename = paste('slv', gamma0, sigma0, h sep = '-')
save(slv1.means.and.vars, file = paste(filename, '.RData', sep = ''))



# ## the analytical results for the stochastic LV model
# graphs.num = length(graphs.20)
# gamma0.max = get.gamma0.max(graphs.20[[graphs.num]]$B)
# sub.graphs.num = 18  # samping uniformly from the set of graphs
# graphs.index = floor(seq(from = 1, to = length(graphs.20), length.out = sub.graphs.num))
# slv1.means.and.vars.analysis = llply(graphs.index, function(index) {
#   analysis.slv1.graph(graphs.20[[index]]$B, gamma0 = gamma0.max, sigma0 = 0.1)
# })
# 

