#!/usr/bin/Rscript

## First step, generate random bipartite graphs with different structural properties.
#source('graphs.rewiring.r')  

## Second step, simulate the stochastic LV2 model
source('slv1.r')

#graph # some graph should has been designated
#beta = c(9, 8)
#h = c(0.01, 0.1, 0.5)

# slv2_25_25_1.5_84 = laply(beta, function(beta0) {
#   laply(h, .parallel = TRUE, function(h0) {
#     sim.slv2.graph(graph = graph, beta0 = beta0, sigma0 = 0.05, h = h0)
#   })
# })


#graphs  # a set of graphs with different nestedness generated by <graph.rewiring.r> should have been designated
sub.graphs.num = 12  # samping uniformly from the set of graphs
graphs.index = floor(seq(from = 1, to = length(graphs), length.out = sub.graphs.num))
A = laply(graphs.index, function(index) {
  sim.slv1.graph(graphs[[index]]$B, beta0 = 1, gamma0 = 1/9)
})

save(A, file = 'slv1.2.RData')



# source('lv2.r')  # Second step, simulate dynamics of mutualistic communities until the equilibrium is approached, modeled by LV2 model.
# source('MOU.r')  # Third step, simulate the stationary dynamics of mutualistic communities in stochatics enviornment, modeled by Multivariate OU process.
