#### Scripts to deal with:
#### 1. the generated graphs outputted by <GenGraphs.R>
#### 2. the generated Mean vectors and variance-covariance matrices 
####    generated by <temporal-stability-lv1.r> and <temporal-stability-lv2.r>

## load result.graphs from data files which has been generated by <GenGraphs.R>
## according to Different Parameters. 
## the parameters are encoded in the name of data files, the encode rule is:
## result.graphs-[plant number]-[animal number]-[average degree]-[No.].RData
load('~/Code/ecological-network/result.graphs-25-25-1.5.RData') 

## load result.lv1
load("~/Code/ecological-network/result.lv1-25-25-1.5-0.RData")
## load result.lv2
load("~/Code/ecological-network/result.lv2-25-25-1.5-0.001-0.RData")


## get the graphs which have random assortativity
result.graphs.0 = list()
for (i in 1:length(result.graphs)) {
  if (result.graphs[[i]]$count.assort == 0) {
    result.graphs.0[[length(result.graphs.0) + 1]] = 
      list(count = result.graphs[[i]]$count, B2 = result.graphs[[i]]$B)
  }
}


## degree heterogeneity and assortativity influence on the mean and variance of species abundance at equilibrium.
s1 = s2 = 25; k = 1.5
Alpha = runif(s1 + s2, min = 2, max = 2)
beta0 = ceiling( sqrt((s1 + s2) * k) )  # squared root of edges number, to ensure the positive definitive of M
D = diag(rep(beta0, s1 + s2))
result.lv1.deterministic = ldply(result.graphs, function(i) {
  B2 = i$B2
  nested.nodf = nested(B2, method = 'NODF')
  B2 = get.adjacency(B2)
  degrees = rowSums(B2)  # the degrees
  heterogeneity = sum(degrees^2) / sum(degrees)  # the degree heterogeneity
  degrees2 = rowSums(B2 %*% B2)  # the two-hop degrees
  assortativity = sum( degrees2 / degrees^2 )
  M = D - B2
  Nstar = solve(M) %*% Alpha  # the feasible fixed point
  abundance.mean = mean(Nstar)
  abundance.sd = sd(Nstar)
  c(index = i$count, index.assort = i$count.assort, nested.nodf = nested.nodf['NODF'],
    heterogeneity = heterogeneity, assortativity = assortativity,
    abundance.mean = abundance.mean, abundance.sd = abundance.sd)
})
result.lv1.deterministic$i = 1:length(result.graphs)
library(akima)
im = with(result.lv1.deterministic, interp(heterogeneity, assortativity, abundance.sd))  # nested.nodf.NODF

with(im,
     filled.contour(x, y, z, col = rainbow(200), nlevels = 200,
                    plot.title = title(main = 'The spectral gap of bipartite ER random graphs', 
                                       xlab = 'Number of species (s)', ylab = 'Average species degree (<k>)'), 
                    key.title = title(main = expression(paste(lambda[1]/lambda[2], sep = ''))),
                    key.axes = axis(4, seq(1.5, 5, by = 0.5)),
                    plot.axes = {axis(1); axis(2) ; contour(x,y,z, add = T, size = 15); contour(x,y,z, nlevels = 1, level = 0, add = T, lwd = 1.5)}
     )
)



library(dplyr)
tmp2 = tmp %.% group_by(index) %.% filter(index.assort == 0) #summarise(length(index.assort))
tmp2 = filter(tmp, index == 18)
tmp2 = select(tmp, -c(index, index.assort))

library(ggplot2)
ggplot(data = tmp, aes(x = i, y = abundance.mean / abundance.sd)) +
  geom_point(size = 1) +  # , alpha = .7, color = 'sky blue', fill = 'sky blue'
  theme_bw()
