Trade off between max eigen of bipartite matrix and norm of inverse of bipartite matrix.
========================================================

<k> increase, gap between largest and second eigenvalue increase; <k> fix, <k^2> increase, gap also increase.

power eigenvalue decompose inverse

### Check the relation between nestedness and fraction of feasible steady states
```{r}
library(igraph)
library(bipartite)
source('nestedness.R')
source('DE.R')
n1 = 25  # number of plants
n2 = 25  # number of animals
connectance = 0.175  # connectance of bipartite network
edges = n1 * n2 * connectance  # number of edges
repeat {  # generate a ER bipartite network that is connected
  G = bipartite.random.game(n1, n2, type = 'gnm', m = edges)
  if (igraph::is.connected(G)) break
}
A = get.incidence(G)  # get its incidence matrix
B = A

totalsteps = 5
stepwise = 20
feasible.nestedness = data.frame(step = numeric(0), nest.cmnb = numeric(0), nest.cmnb2 = numeric(0), nest.nodf = numeric(0), nest.nodf2 = numeric(0), feasible.frac = numeric(0), feasible.lev.mean = numeric(0), feasible.lev.sd = numeric(0))
for (i in 1:totalsteps) {  
  # for each network with optimized nestedness, check fraction of their feasible steady states
  lv2.survived = data.frame(lv2.check(A, extinct.threshold = 10^-8))
  for (j in 1:499) {  
    lv2.survived = rbind(lv2.survived, lv2.check(A, extinct.threshold = 10^-8))
  }
  feasible.frac = sum(lv2.survived$extinct == 0) / 500  # fraction of feasible solution
  feasible.lev.mean = mean(subset(lv2.survived, select = lev, extinct == 0)$lev)  # LEV of feasible states
  feasible.lev.sd = sd(subset(lv2.survived, select = lev, extinct == 0)$lev)
  tmp = data.frame(step = i, nest.cmnb = nest.cmnb(A)$CMNB, nest.cmnb2 = nest.cmnb2(A)$CMNB, nest.nodf = nest.nodf(A)$NODF, nest.nodf2 = nest.nodf2(A)$NODF, feasible.frac = feasible.frac, feasible.lev.mean = feasible.lev.mean, feasible.lev.sd = feasible.lev.sd)
  feasible.nestedness = rbind(feasible.nestedness, tmp)
  
  A = rewirelinks.richer(A, stepwise)  # Optimize nestedness by rewiring links between species
  print(i)
}

```

```{r}
b = a
# visweb(a)

d = 2 * edges / (n1 + n2)  # the elements on the diagonal
D =  50 * diag(rep(d, n1 + n2), ncol = n1 + n2)  # construct a diagonal matrix

totalsteps = 100
stepwise = 100
a1 = as.one.mode(a)
a2 = a1 %*% a1
tr4 = sum(a2^2)
a1 = D - a1
maxeigen = max(eigen(a1)$values)
maxeigen.inv = max(eigen(solve(a1))$values)
norm.inv = sum(solve(a1))
df.nestedness = data.frame(step = 0, nest.cmnb = nest.cmnb(a)$CMNB, nest.cmnb2 = nest.cmnb2(a)$CMNB, nest.nodf = nest.nodf(a)$NODF, nest.nodf2 = nest.nodf2(a)$NODF, maxeigen = maxeigen, norm.inv = norm.inv, tr4 = tr4, maxeigen.inv = maxeigen.inv, lv2.check(a))
for (i in 1:totalsteps) {
  a = rewirelinks.richer(a, stepwise)
  a1 = as.one.mode(a)
  a2 = a1 %*% a1
  tr4 = sum(a2^2)
  a1 = D - a1
  maxeigen = max(eigen(a1)$values)
  maxeigen.inv = max(eigen(solve(a1))$values)
  norm.inv = sum(solve(a1))
  df.nestedness = rbind(df.nestedness, data.frame(step = i, nest.cmnb = nest.cmnb(a)$CMNB, nest.cmnb2 = nest.cmnb2(a)$CMNB, nest.nodf = nest.nodf(a)$NODF, nest.nodf2 = nest.nodf2(a)$NODF, maxeigen = maxeigen, norm.inv = norm.inv, tr4 = tr4, maxeigen.inv = maxeigen.inv, lv2.check(a)))
  print(i)
}


```



```{r}
ns = seq(100, 1000, by = 100)
steps = seq(1, 10)
gap.bipartite = ldply(ns, function(n) {
  G = graph.connected(s = c(n, n), k = 4, gtype = 'bipartite')  # generate a random connected bipartite graph
  A = igraph::get.incidence(G)
  ldply(steps, .parallel = TRUE, function(step) {
    print(paste(n, step))    
    B = rewirelinks.richer(A, HowManyToTry = step * 500)
    B = swaplinks(B, HowManyToTry = 5000)
    C = get.adjacency(B)
    hk = sum(rowSums(C)^2)
    sk = sum(rowSums(C))
    lev = eigen(C)$values[1]
    sev = eigen(C)$values[2]
    # mev = eigen(B)$values[n]
    r = lev / sev
    c(n, step, hk, sk, r, lev, sev)
  })
})
colnames(gap.bipartite2) <- c('n', 'step', 'hk', 'sk', 'r', 'lev', 'sev')
gap.bipartite2$chk = gap.bipartite2$hk / gap.bipartite2$sk
ggplot(data = gap.bipartite2, aes(x = chk, y = r)) +
  geom_line() +
  facet_wrap(~n, scales = 'free')


```



You can also embed plots, for example:

```{r fig.width=7, fig.height=6}
library(agridat)

federer.tobacco <- federer.tobacco[order(as.numeric(federer.tobacco$block), as.numeric(federer.tobacco$row)),]

federer.tobacco$dose <- factor(federer.tobacco$dose)

levelplot(dose ~ as.numeric(block)*rev(as.numeric(row)), 
          scales=list(x=list(at=NULL), y=list(at=as.numeric(federer.tobacco$row), 
                                              labels=as.character(rev(as.numeric(federer.tobacco$row))))),
          aspect=0.4, panel=function(x,y,...) {
  panel.levelplot(x,y,...)
  grid.lines(x=c(0.125,0.125), y=c(0,1), default.units="npc", gp=gpar(lwd=2))
  grid.lines(x=c(0.25,0.25), y=c(0,1), default.units="npc", gp=gpar(lwd=2))
  grid.lines(x=c(0.375,0.375), y=c(0,1), default.units="npc", gp=gpar(lwd=2))
  grid.lines(x=c(0.5,0.5), y=c(0,1), default.units="npc", gp=gpar(lwd=2))
  grid.lines(x=c(0.625,0.625), y=c(0,1), default.units="npc", gp=gpar(lwd=2))
  grid.lines(x=c(0.75,0.75), y=c(0,1), default.units="npc", gp=gpar(lwd=2))
  grid.lines(x=c(0.875,0.875), y=c(0,1), default.units="npc", gp=gpar(lwd=2))
  ltext(x=x, y=y, label=federer.tobacco$dose, cex=1)
}, xlab="", ylab="field row", 
main="Federer tobacco height field layout with\nseed radiation dose treatment allocation", 
colorkey=FALSE, data=federer.tobacco,
par.settings=list(regions=list(col=col2(100))))
trellis.focus("panel", 1, 1, clip.off=TRUE)
grid.text("I", 0.06, 1.04)
grid.text("II", 0.185, 1.04)
grid.text("III", 0.31, 1.04)
grid.text("IV", 0.435, 1.04)
grid.text("V", 0.56, 1.04)
grid.text("VI", 0.685, 1.04)
grid.text("VII", 0.81, 1.04)
grid.text("VIII", 0.935, 1.04)
trellis.unfocus()
```



